[workspace]

[package]
name = "turingapigen"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
convert_case = "0.10.0"
regex = "1.12.2"
serde = { version = "1.0.228", features = ["derive"] }
tera = "1.20.0"

